# -*- coding: utf-8 -*-
"""Copy of Sentimen Analysis TF IDF Uniform LR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AhvN21lC1p-R0lB3hM0UHIi3VVr-r_j

1. IMPORT LIBRARY
"""

pip install Sastrawi

import re
import time
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, precision_score, recall_score,
    f1_score, ConfusionMatrixDisplay
)

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

""" 2. LOAD DATASET"""

url = 'https://drive.google.com/uc?export=download&id=1_4rclCT72WkwfSPh_jhJ6YQKCWKDaByw'

try:
    # Menggunakan sep='\t' karena data dipisahkan oleh Tab
    df = pd.read_csv(url, sep='\t', on_bad_lines='skip')

    print(df.head())
except Exception as e:
    print(f"Terjadi kesalahan saat membaca data: {e}")

"""3. EXPLORATORY DATA ANALYSIS (EDA)"""

print("\n[3] EXPLORATORY DATA ANALYSIS")
print("-" * 40)

label_map = {1: "Positif", 0: "Netral", -1: "Negatif"}
df["label_nama"] = df["sentimen"].map(label_map)

# Distribusi label
print("\nDistribusi Label:")
dist = df["label_nama"].value_counts()
print(dist)
print(f"\nPersentase:")
print((dist / len(df) * 100).round(2).astype(str) + "%")

# Panjang tweet
df["panjang"] = df["Tweet"].apply(lambda x: len(str(x).split()))
print("\nStatistik panjang tweet (kata):")
print(df.groupby("label_nama")["panjang"].describe().round(2))

# ─── Plot EDA ───
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("EDA – Indonesian Sentiment Twitter Dataset", fontsize=14, fontweight="bold")

# (a) Pie chart
color_map = {"Positif": "#4CAF50", "Netral": "#9E9E9E", "Negatif": "#F44336"}
colors_pie = [color_map[l] for l in dist.index]
axes[0].pie(dist.values, labels=dist.index, autopct="%1.1f%%",
            colors=colors_pie, startangle=90)
axes[0].set_title("Distribusi Sentimen")

# (b) Bar chart
bar_colors = [color_map[l] for l in dist.index]
bars = axes[1].bar(dist.index, dist.values, color=bar_colors, edgecolor="black")
axes[1].set_title("Jumlah Data per Kelas")
axes[1].set_xlabel("Sentimen")
axes[1].set_ylabel("Jumlah")
for bar, val in zip(bars, dist.values):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 30,
                 str(val), ha="center", fontweight="bold", fontsize=11)

# (c) Boxplot panjang tweet
order = ["Positif", "Netral", "Negatif"]
sns.boxplot(data=df, x="label_nama", y="panjang",
            palette=color_map, order=order, ax=axes[2])
axes[2].set_title("Distribusi Panjang Tweet per Sentimen")
axes[2].set_xlabel("Sentimen")
axes[2].set_ylabel("Jumlah Kata")

plt.tight_layout()
plt.savefig("eda_plot.png", dpi=150, bbox_inches="tight")
plt.show()

print("\n[4] PRAPROSES TEKS")
print("-" * 40)

import re
import time

# =========================================
# CEK NAMA KOLOM DATASET
# =========================================

print("Kolom dataset:")
print(df.columns)

# GANTI SESUAI DATASET KAMU
kolom_teks  = "Tweet"
kolom_label = "sentimen"


# =========================================
# STOPWORD
# =========================================

# =========================================
# STOPWORD INDONESIA + INFORMAL + MALAYSIA
# =========================================

STOPWORDS_ID = {

    # Pronouns
    "saya", "kamu", "dia", "aku", "kami", "kita",
    "mereka", "beliau", "kalian", "nya", "kau",

    # Conjunctions / umum
    "dan", "atau", "tapi", "tetapi", "namun",
    "juga", "serta", "dengan", "bahwa",
    "karena", "sebab", "kalau", "jika",
    "bila", "meski", "walaupun", "maka",
    "supaya", "agar", "lalu", "kemudian",

    # Prepositions
    "di", "ke", "dari", "untuk", "kepada",
    "oleh", "pada", "tentang", "dalam",
    "atas", "bawah", "antara", "tanpa",
    "sampai", "sejak", "hingga",
    "selama", "setelah", "sebelum","buat",

    # Articles / Determiners
    "yang", "ini", "itu", "tersebut",
    "suatu", "sebuah", "semua", "setiap",
    "para", "hal", "apa", "siapa",
    "mana", "dimana",

    # General words
    "adalah", "akan", "ada",
    "saja", "pun",

    # Adverbs
    "sangat", "belum", "pernah",
    "selalu", "sering", "masih", "kadang",
    "paling", "hanya", "cuma",
    "memang", "emang",

    # Twitter / informal particles
    "sih", "deh", "dong", "nih", "tuh",
    "ya", "yah", "kok", "lah",
    "mah", "kan", "loh",

    # Noise words
    "weh", "woi", "bro", "sis",
    "min", "admin",

    # Informal words
    "aja", "udah", "gitu",
    "orang", "hari", "sama", "baru",
    "kayak", "kalo",
    "pastu", "lepas",
    "macam", "mcm",
    "dekat", "kat",

    # Malaysian / informal particles
    "dah", "nak",
    "aje", "je",
    "gak", "ngak",
    "yuk", "ayo", "hayoo","and",
}

# =========================================
# SLANG NORMALIZATION
# =========================================

SLANG_DICT = {

    # negasi
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "ngga": "tidak",
    "tak": "tidak",
    "ntar": "nanti",

    # umum
    "bgt": "banget",
    "bgtt": "banget",
    "aja": "saja",
    "ni": "ini",
    "udh": "sudah",
    "sm": "sama",
    "tp": "tapi",
    "krn": "karena",
    "dr": "dari",
    "dlm": "dalam",
    "maksudnya": "maksud",
    "katanya": "kata",
    "rasanya": "rasa",
    "jalannya": "jalan",
    "kerjanya": "kerja",

    # pronoun
    "gw": "saya",
    "gua": "saya",
    "gue": "saya",
    "lu": "kamu",
    "loe": "kamu",

    # ekspresi
    "wkwk": "tertawa",
    "wkwwk": "tertawa",
    "haha": "tertawa",
    "hehe": "tertawa",

    # typo umum
    "mantul": "mantap",
    "kerennn": "keren",
    "jelekk": "jelek"
}


# =========================================
# FUNGSI PREPROCESS
# =========================================

def praproses(teks):

    # ---------------------------------
    # lowercase
    # ---------------------------------
    teks = str(teks).lower()

    # ---------------------------------
    # hapus URL
    # ---------------------------------
    teks = re.sub(r"http\S+|www\S+", "", teks)

    # ---------------------------------
    # hapus mention & hashtag
    # ---------------------------------
    teks = re.sub(r"@\w+", "", teks)
    teks = re.sub(r"#\w+", "", teks)

    # ---------------------------------
    # normalisasi ekspresi
    # ---------------------------------
    teks = re.sub(r"(huhu)+", " sedih ", teks)
    teks = re.sub(r"(haha)+|(hehe)+|(wkwk)+|(awokwok)+", " tertawa ", teks)

    # ---------------------------------
    # normalisasi huruf berulang
    # contoh:
    # lucuuuu -> lucuu
    # kereeeennn -> kereenn
    # ---------------------------------
    teks = re.sub(r'(.)\1{2,}', r'\1\1', teks)

    # ---------------------------------
    # hapus angka & simbol
    # ---------------------------------
    teks = re.sub(r"[^a-z\s]", " ", teks)

    # ---------------------------------
    # hapus spasi berlebih
    # ---------------------------------
    teks = re.sub(r"\s+", " ", teks).strip()

    # ---------------------------------
    # tokenisasi
    # ---------------------------------
    tokens = teks.split()

    teks = re.sub(r'([a-z])([A-Z])', r'\1 \2', teks)

    hasil = []

    for token in tokens:

        # slang normalization
        token = SLANG_DICT.get(token, token)

        # stopword removal
        if token not in STOPWORDS_ID:
            hasil.append(token)

    # hapus token terlalu pendek
    hasil = [t for t in hasil if len(t) > 2]

    return " ".join(hasil)


# =========================================
# PROSES PREPROCESSING
# =========================================

print(f"\nMemproses {len(df)} tweet...")

t0 = time.time()

df["teks_bersih"] = df[kolom_teks].astype(str).apply(praproses)

elapsed = time.time() - t0

print(f"Praproses selesai dalam {elapsed:.1f} detik.")


# =========================================
# CONTOH HASIL
# =========================================

print("\nContoh hasil praproses:\n")

for i in range(5):

    print(f"[{df[kolom_label].iloc[i]}]")

    print("Asli   :", df[kolom_teks].iloc[i][:100])

    print("Bersih :", df["teks_bersih"].iloc[i][:100])

    print("-" * 60)

"""4. PRAPROSES TEKS"""

factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Panjang setelah praproses
df["panjang_bersih"] = df["teks_bersih"].apply(lambda x: len(str(x).split()))

# ─── Visualisasi sebelum vs sesudah praproses ───
fig2, axes2 = plt.subplots(1, 2, figsize=(14, 4))
fig2.suptitle("Perbandingan Panjang Tweet Sebelum & Sesudah Praproses", fontsize=13, fontweight="bold")

sns.histplot(df["panjang"], bins=30, color="#1976D2", ax=axes2[0], kde=True)
axes2[0].set_title("Sebelum Praproses")
axes2[0].set_xlabel("Jumlah Kata")
axes2[0].set_ylabel("Frekuensi")

sns.histplot(df["panjang_bersih"], bins=30, color="#E53935", ax=axes2[1], kde=True)
axes2[1].set_title("Sesudah Praproses + Stemming")
axes2[1].set_xlabel("Jumlah Kata")
axes2[1].set_ylabel("Frekuensi")

plt.tight_layout()
plt.savefig("praproses_comparison.png", dpi=150, bbox_inches="tight")
plt.show()
print(">> Plot perbandingan praproses disimpan: praproses_comparison.png")
print(f"   Rata-rata kata sebelum : {df['panjang'].mean():.1f}")
print(f"   Rata-rata kata sesudah : {df['panjang_bersih'].mean():.1f}")

"""5. TRAIN-TEST SPLIT"""

print("\n[5] TRAIN-TEST SPLIT")
print("-" * 40)

X = df["teks_bersih"]
y = df["sentimen"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Total data   : {len(df)}")
print(f"Data latih   : {len(X_train)} ({len(X_train)/len(df)*100:.0f}%)")
print(f"Data uji     : {len(X_test)} ({len(X_test)/len(df)*100:.0f}%)")
print(f"\nDistribusi label - latih:\n{y_train.value_counts().rename(label_map)}")
print(f"\nDistribusi label - uji:\n{y_test.value_counts().rename(label_map)}")

"""6. VEKTORISASI / EMBEDDING (TF-IDF Unigram)"""

print("\n[6] VEKTORISASI - TF-IDF UNIGRAM")
print("-" * 40)

tfidf = TfidfVectorizer(
    ngram_range=(1, 1),   # Unigram
    max_features=15000,    # Maksimal feature
    min_df=3,             # Kata muncul minimal 1 dokumen
    sublinear_tf=True     # Pakai log(TF) untuk meredam frekuensi tinggi
)

X_train_vec = tfidf.fit_transform(X_train)
X_test_vec  = tfidf.transform(X_test)

print(f"Ukuran matriks TF-IDF latih : {X_train_vec.shape}")
print(f"Ukuran matriks TF-IDF uji   : {X_test_vec.shape}")
print(f"Jumlah fitur (vocab)         : {len(tfidf.vocabulary_)}")
print(f"\nFitur (token):")
print(list(tfidf.vocabulary_.keys()))

"""7. TRAINING MODEL (Logistic Regression)"""

print("\n[7] TRAINING MODEL - LOGISTIC REGRESSION")
print("-" * 40)

model = LogisticRegression(
    C=1.0,              # Regularisasi (default)
    max_iter=1000,
    solver="lbfgs",
    random_state=42
)
class_weight="balanced"
model.fit(X_train_vec, y_train)
print("Model berhasil dilatih!")
print(f"Kelas yang dipelajari  : {model.classes_} → {[label_map[c] for c in model.classes_]}")

"""8. PREDIKSI"""

print("\n[8] PREDIKSI")
print("-" * 40)

y_pred = model.predict(X_test_vec)
y_prob = model.predict_proba(X_test_vec)

print("Hasil Prediksi vs Label Sebenarnya (data uji):")
hasil_pred = pd.DataFrame({
    "Komentar"  : X_test.values,
    "Aktual"    : y_test.map(label_map).values,
    "Prediksi"  : pd.Series(y_pred).map(label_map).values,
    "Benar?"    : ["True" if a == p else "False"
                   for a, p in zip(y_test.values, y_pred)]
})
print(hasil_pred.head(10).to_string(index=False))

""" 9. EVALUASI MODEL"""

print("\n[9] EVALUASI MODEL")
print("-" * 40)

acc = accuracy_score(y_test, y_pred)
print(f"Akurasi : {acc:.4f} ({acc*100:.2f}%)\n")

target_names = ["Negatif (-1)", "Netral (0)", "Positif (1)"]
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=[-1, 0, 1])
print("Confusion Matrix:")
print(cm)

# --- Plot Confusion Matrix ---
fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=["Negatif", "Netral", "Positif"])
disp.plot(ax=ax, cmap="Blues", colorbar=False)
ax.set_title("Confusion Matrix - TF-IDF Unigram + Logistic Regression",
             fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()
print(">> Plot Confusion Matrix disimpan: confusion_matrix.png")

# Top fitur per kelas
print("\nTop 10 Fitur Paling Berpengaruh per Kelas:")
feature_names = np.array(tfidf.get_feature_names_out())
for i, cls in enumerate(model.classes_):
    top10_idx = np.argsort(model.coef_[i])[-10:][::-1]
    print(f"\n  [{label_map[cls]}] → {[feature_names[j] for j in top10_idx]}")

import pickle

# simpan model
pickle.dump(model, open("model.pkl", "wb"))

# simpan vectorizer
pickle.dump(tfidf, open("vectorizer.pkl", "wb"))

import sys
!{sys.executable} -m pip install streamlit
import streamlit as st
import pickle
import re

from google.colab import files

files.download("model.pkl")
files.download("vectorizer.pkl")